src/serialization/write/mod.rs, src/write/file.rs, src/write/mod.rs
This exposes these two to `write_file`, which are needed when people want to write metadata to the file.
=> Allowed writing metadata and created_by

integration/write_pyarrow.py, src/encoding/mod.rs, src/encoding/plain_byte_array/decoder.rs, src/encoding/plain_byte_array/mod.rs, src/lib.rs, src/serialization/read/binary.rs, src/serialization/read/mod.rs
Support for plain encoded binary columns (used when all/most values in the column are distinct), split out from #7.
I now remember that this is the same logic as in `page_dict::binary::read_plain` so it might make sense to reuse the iterator there. The iterator should get a `size_hint` function so the correct capacity gets allocated.
=> Support for plain encoded binary in data pages

src/metadata/column_chunk_metadata.rs, src/metadata/schema_descriptor.rs, src/read/mod.rs, src/read/page_iterator.rs, src/read/statistics/mod.rs, src/serialization/read/mod.rs, src/serialization/write/mod.rs
This also simplifies the naming of some methods of the `ColumnMetadata`.
=> Added method to read columns' statistics.

Cargo.toml, README.md, src/compression.rs, src/error.rs, src/metadata/column_chunk_metadata.rs, src/read/compression.rs, src/read/mod.rs, src/read/page.rs, src/read/page_dict/mod.rs, src/read/page_iterator.rs, src/serialization/read/binary.rs, src/serialization/read/boolean.rs, src/serialization/read/mod.rs, src/serialization/read/primitive.rs, src/serialization/read/primitive_nested.rs, src/serialization/read/record_batch.rs, src/serialization/write/mod.rs, src/serialization/write/primitive.rs, src/write/compression.rs, src/write/mod.rs, src/write/page.rs
This allows re-using the page buffers, thereby reducing alloc and free when reading multiple pages.
=> Improved API to re-use page buffers

src/lib.rs, src/metadata/column_chunk_metadata.rs, src/read/page.rs, src/serialization/read/mod.rs, src/serialization/write/mod.rs, src/serialization/write/primitive.rs, src/statistics/binary.rs, src/statistics/mod.rs, src/statistics/primitive.rs
This allows the statistics to be deserialized from the correct logical types (e.g. deserialize i32 stats to a u8 stats)
=> Added descriptor to statistics.

Cargo.toml, src/serialization/write/mod.rs, src/write/dyn_iter.rs, src/write/file.rs, src/write/mod.rs, src/write/row_group.rs, src/write/stream.rs
This generalizes the `write_file` by allowing dynamic iterators. The penalty should be low because these iterators have a low performance footprint.
Also added `write_stream`, which is the `async` version of `write_file` (for streams, like DataFusion).
=> Allow writing a file from a stream

integration/write_pyarrow.py, src/read/compression.rs, src/serialization/read/binary.rs, src/serialization/read/levels.rs, src/serialization/read/mod.rs, src/serialization/read/primitive.rs, src/serialization/read/primitive_nested.rs
Also added integration tests against pyarrow for the following:
* int, float, bool, string, date
* nullable and required
* version 1 and 2
* dict encoded and non-dict encoded
* compressed and uncompressed
validating that we can read all combinations of the above.
=> Fixed bug in decompressing v2

src/encoding/mod.rs, src/read/levels.rs
Noticed this giving incorrect results when working on support for required lists or lists with required items. Previously, lists always assumed a maximum definition level of 3, for which the implementation returned a correct result. But for a max level of 1 or 2 the result should actually be different from the log2. At the same time the implementation can be optimized by using the `leading_zeros` intrinsic.
=> Tests and fix for get_bit_width function

integration-tests/src/write/primitive.rs, src/encoding/bitpacking.rs, src/encoding/hybrid_rle/bitmap.rs, src/encoding/hybrid_rle/encoder.rs, src/encoding/hybrid_rle/mod.rs
We currently only support RLE-hybrid encoding for booleans. However, to write nested types with def and rep levels larger than 1, we need to encode values larger than 1.
This implements RLE-hybrid encoding for `u32`. The implementation does not allocate on the heap.
=> Added RLE-hybrid encoding for u32

Cargo.toml
Upgrade zstd a couple of versions
=> Upgrade zstd

integration-tests/src/read/mod.rs, src/read/mod.rs, src/read/page_iterator.rs
This PR adds an ability to push filtering to individual data pages when reading. This is useful because individual pages also have statistics in their header that can be used to filter.
The function `get_page_iterator` now expects an optional `Arc<Fn(&ColumnDescriptor, &DataPageHeader) -> bool>` that can be used to skip the page from the iteration.  To migrate, pass `None` or a `Some(Arc(|_,_| true))` to recover the previous behavior.
=> Added option to apply filter pushdown to data pages.

Cargo.toml, src/write/column_chunk.rs, src/write/dyn_iter.rs, src/write/file.rs, src/write/mod.rs, src/write/page.rs, src/write/row_group.rs, src/write/stream.rs, src/write/stream_stream.rs
This PR adds support to write to `AsyncWrite + AsyncSeek (+ Unpin + Send)`.
The need for `AsyncSeek` is due to a current limitation of thrift that does not report how many bytes were written in their protocols. This implementation only calls `seek` of `SeekFrom::Current(0)` before and after writing to compute how much bytes were written between the calls.
* `DynIter` no longer has a lifetime parameter (it was not needed and made the `async` implementation more difficult).
=> Added support to write to async writers.

README.md, examples/s3/src/main.rs, integration-tests/src/read/mod.rs, parquet-tools/src/lib/dump.rs, src/read/mod.rs, src/read/page_stream.rs
old:
```rust
pub fn get_page_iterator<'a, RR: Read + Seek>(metadata: &FileMetaData, row_group: usize, column: usize, ...)
```
new:
```rust
pub fn get_page_iterator<'a, RR: Read + Seek>(column_metadata: &ColumnChunkMetaData, ...)
```
it makes it a bit more explicit and users usually already get the column metadata, to get the file descriptor and stats (code duplication of consumers).
To migrate, 
before:
```rust
let compressed_pages = get_page_iterator(&metadata, row_group, column, &mut file, file)?.collect()?;
```
after:
```rust
let column_meta = metadata.row_groups[row_group].column(column);
let compressed_pages = get_page_iterator(column_meta, &mut file, file)?.collect()?;
```
=> Simplified API to get page iterator

integration-tests/src/read/binary.rs, integration-tests/src/read/primitive.rs, integration-tests/src/read/primitive_nested.rs, src/page/mod.rs, src/read/compression.rs, src/read/levels.rs
Reduces the consumer code necessary to split and deserialize a page.
* `split_buffer_v1` and `split_buffer_v2` were moved from `levels::` to `page::` (since they split the page buffer)
=> Simplified split of page buffer

Cargo.toml, src/write/column_chunk.rs, src/write/file.rs, src/write/page.rs, src/write/row_group.rs, src/write/stream.rs, src/write/stream_stream.rs
Many remote writers (e.g. s3) either do not support such a requirement or making them are expensive and/or brittle.
Also closes #45.
=> Removed requirement of "Seek" on write.

integration-tests/src/read/binary.rs, integration-tests/src/read/primitive.rs
As @jhorstmann wrote in #7 , dictionaries indices are RLE hybrid encoded, this PR changes the integration tests to that.
=> Made tests deserializer use the correct decoder.

src/compression.rs, src/parquet_bridge.rs
I've just noticed the typo while writing a Zstd compressed Parquet.
=> Compression enum typo

integration-tests/src/read/binary.rs
The java parquet writer seems to write required fields using BitPacked encoding for the definition levels. With a max definition level of zero this encoding also does not use any space in the file and instead can be decoded to an iterator of zeros.
=> BitPacked encoding with max_def_level 0 should also result in an iterator of zeros

src/encoding/hybrid_rle/decoder.rs, src/encoding/hybrid_rle/mod.rs
When the decoder has a zero bit width, it means that it is always the same value (`0`). We did not take this edge case into account.
=> Fixed error in reading zero-width bit from hybrid RLE.

src/statistics/fixed_len_binary.rs, src/statistics/mod.rs
Hi,
This pull request is related to [arrow2#444](https://github.com/jorgecarleitao/arrow2/issues/444).
I just simply modify the Fix Len Statistics and it constructors to help facilitate more logical type from fix-len binary
=> Add descriptor to `FixedLenStatistics`

src/write/statistics.rs
Hello,
I wrote a small changes to write module to write reduced statistics for  `FixedLenByteArray` as well.
To address the issue [here](https://github.com/jorgecarleitao/arrow2/issues/444)
I don't know how to write macro properly yet so I just simply copy over the function `reduce_binary`
=> Add writing reduced statistics for `FixedLenByteArray`

src/encoding/delta_bitpacked/decoder.rs
The input bytes were never consumed while going to the next mini-block,
leading to some very interesting values.
I couldn't find anything with enough data in `parquet-testing` so I wrote a small test case. It works for all the files I've tested created
by the `parquet` crate, though.
=> Fixed delta-bitpacked mini-block decoding

.github/workflows/test.yml, .gitignore, integration-tests/integration/write_pyarrow.py, integration-tests/src/lib.rs, integration-tests/src/read/boolean.rs, integration-tests/src/read/mod.rs, integration-tests/src/read/struct_.rs, src/encoding/bitpacking.rs, src/encoding/hybrid_rle/mod.rs, src/read/compression.rs, src/read/mod.rs, src/read/page_iterator.rs
This PR contains basic APIs to read nested structures from parquet, while keeping the principle of separation of IO-bounded from CPU-bounded operations. In this context, this PR declares an iterator-like trait to support this because it allows users to, as before, collect all the relevant pages of columns and parallelize CPU.
This use-case is interesting from Rust's perspective because it requires an iterator-like (of columns) that returns iterators (of compressed pages), each of them needs to make `.read` calls. This implies that the column iterator must keep ownership of the page iterators so that it can move the reader from iterator to iterator. At the same time, the individual iterators must be mutable so that they can call `.read`.
The API for this:
```rust
pub trait …
```
=> Added basic support to read nested types

src/encoding/mod.rs, src/read/compression.rs, src/read/page_iterator.rs
This PR improves buffer reuse by avoiding a memcopy of data that is about to be re-written.
Performance downstream (`arrow2`)
```
read utf8 multi 2^20    time:   [7.2616 ms 7.3060 ms 7.3530 ms]                                 
change: [-17.488% -16.369% -15.395%] (p = 0.00 < 0.05)
```
=> Improved performance of reading multiple pages

src/write/dyn_iter.rs, src/write/stream.rs, src/write/stream_stream.rs
When writing stream of row groups, usually computing the stream's item is CPU-bounded and may need to be done in a different thread than the runtime one. However, the access to the next item of the stream may not need to wait for its evaluation.
This means that the values of the stream itself may not be available immediately after the stream yields, and may be available only at a later point in time (when `.await`).
This pattern (stream of futures) is common in Rust (e.g. it is the signature for [`futures::stream.buffered`](https://docs.rs/futures/0.3.18/futures/stream/struct.Buffered.html)), as it allows multiple items from a stream to be evaluated concurrently, since the stream can progress for as long as the consumer can accept running multiple items at the same time.
This PR changes …
=> Changed stream of groups to stream of futures of groups

src/metadata/column_chunk_metadata.rs, src/metadata/row_metadata.rs
To create metadata and construct tests for filter push down in DataFusion
=> Add constructor to RowGroupMetaData and ColumnChunkMetaData

src/encoding/bitpacking.rs
This PR reduces memory allocations by replacing a heap allocated buffer
with a stack allocated buffer in the bitpacking decode path.
=> bitpacking: use stack-allocated temporary buffer

Cargo.toml
zstd has released [version 0.11](https://github.com/gyscos/zstd-rs/releases/tag/v0.11.0) with Web Assembly support https://github.com/gyscos/zstd-rs/pull/139.
=> Update zstd version for wasm support

integration-tests/src/read/mod.rs, src/encoding/delta_bitpacked/encoder.rs, src/metadata/row_metadata.rs, src/schema/io_message/from_message.rs, src/schema/io_thrift/to_thrift.rs, src/write/column_chunk.rs, src/write/file.rs, src/write/row_group.rs, src/write/statistics.rs
* afaik `ordinal` is used for id-based row group selection
* `total_compressed_size` to get a rough size of the data
=> Added `ordinal` and `total_compressed_size` to column meta

Cargo.toml, examples/read_metadata.rs, guide/src/README.md, src/bloom_filter/hash.rs, src/bloom_filter/mod.rs, src/bloom_filter/read.rs, src/bloom_filter/split_block.rs, src/lib.rs
This PR adds support to read and use bloom filters to skip row groups. See more details [here](https://github.com/apache/parquet-format/blob/master/BloomFilter.md), as well as the addition to the example where a bloom filter from a parquet file is used to check if a value is (not) on a column from a row group.
This tool is essentially an improvement over using statistics, to skip row groups.
This PR also adds the necessary algorithms to write bloom filters, but does not provide an API do so (yet), as usually bloom filters are created while serializing pages, which requires a larger change, as we currently only receive compressed pages, over which we can't create a bloom filter from
Close #98
=> Added support to read and use bloom filters

src/parquet_bridge.rs, src/read/compression.rs, src/read/mod.rs, src/read/page/mod.rs, src/read/page/reader.rs, src/read/page/stream.rs, src/read/page_iterator.rs, src/write/column_chunk.rs
* Renamed it to `PageReader`
* Added trait `PageIterator`
* Removed internal state for page index, since page indexes are only present in metadata
=> Simplified `PageIterator`

src/deserialize/hybrid_rle.rs, src/deserialize/mod.rs, src/deserialize/utils.rs, src/indexes/intervals.rs, src/indexes/mod.rs, src/page/mod.rs, src/read/compression.rs, src/read/page/indexed_reader.rs, src/read/page/reader.rs, src/write/compression.rs, src/write/page.rs, tests/it/read/primitive.rs, tests/it/write/binary.rs, tests/it/write/indexes.rs, tests/it/write/mod.rs, tests/it/write/primitive.rs
This PR fixes a design mistake in how filtered pages should be represented. 
The examples in #102 assumed that a page would only overlap with a single row interval. However, it is possible for multiple row intervals to overlap a single page. The current API in main does not cater for this.
This PR fixes this, therefore closing #102.
Tests demonstrate how a column with pages containing
```rust
let page1 = vec![Some(0), Some(1), None, Some(3), Some(4), Some(5), Some(6)];
let page2 = vec![Some(10), Some(11)];
```
and the selection `let intervals = &[Interval::new(2, 2)];` (start, length) yields `vec![None, Some(3)])]`.
In this model, we do not decompress nor deserialize page2, and we do not deserialize the remaining items from page1.
Closes #102
=> Fixed design error in filtered pages

src/compression.rs, tests/it/main.rs, tests/it/write/mod.rs
Issue 
- #117
By using `lz4::block::compress_bound` to determine the size of output buffer
=> Fix Lz4Raw compression error (if input is tiny) 

Cargo.toml
The `(de)compress_to_buffer` API we're using was only added in 1.23.3
=> Fix minimum version for LZ4

src/deserialize/filtered_rle.rs, src/deserialize/hybrid_rle.rs, src/deserialize/mod.rs, src/deserialize/utils.rs, tests/it/read/deserialize.rs, tests/it/read/mod.rs, tests/it/read/utils.rs
This PR adds an iterator adapter that can skip sections of hybrid-RLE encoded definition levels used in optional data pages.
This adapter is a specialization suitable for index-reading pages to in-memory formats that use bitmaps (like arrow).
=> Added specialized deserialization of one-level filtered pages

src/write/file.rs
Page offsets do not require statistics and can always be written. Given how important and small they are, let's just write them.
=> Made offsets be always written

src/write/column_chunk.rs
Sort the encodings in column metadata as there's no defined order within
the `HashSet`.
I discovered this while comparing identical files at the byte level.
=> Deterministic encodings in metadata

.github/workflows/test.yml, Cargo.toml, src/compression.rs, src/error.rs
This PR was done together with @kylebarron and adds an optional dependency lz4-flex by @PSeitz as a LZ4 compressor/decompressor.
This implementation a bit slower but uses no `unsafe` and is written in native Rust, therefore supporting being compiled to wasm.
=> Add optional LZ4 flex

src/write/file.rs, tests/it/write/indexes.rs, tests/it/write/mod.rs
The user may want to finish the file without consuming the writer, i.e. the semantics of consuming the writer (memory management) should be independent of the semantics of ending the file (parquet specification)
=> Made `.end` not consume the parquet `FileWriter`

src/compression.rs, src/parquet_bridge.rs, src/write/compression.rs, tests/it/write/indexes.rs, tests/it/write/mod.rs
Following from the [previous draft request](https://github.com/jorgecarleitao/parquet2/pull/121) for optional `zstd` compression levels
=> Add CompressionOptions, which allows for zstd compression levels.

Cargo.toml, benches/decode_bitpacking.rs, src/encoding/bitpacking.rs
Inlining `next` yields a major improvement
=> Improved perf of bitpacking decoding (3.5x)

Cargo.toml, benches/decode_rle.rs, src/encoding/hybrid_rle/decoder.rs
Same idea as #129 - inlining `next` has performance implications
=> Improved performance of RLE decoding (-18%)

src/compression.rs, src/parquet_bridge.rs, tests/it/write/mod.rs
* Sets the default GZIP compression == 6, as this is the default within miniz_oxide.
* brotli quality is kept the same, as no default was listed with the brotli rust crate.
This is a breaking API change. However, it is an extension of the previous breaking change to zstd levels.
=> Added compression options/levels for GZIP and BROTLI codecs.

src/read/mod.rs, src/read/page/indexed_reader.rs, src/read/page/mod.rs, src/read/page/reader.rs, src/read/page/stream.rs
=> Added new_with_page_meta to PageReader

src/compression.rs
There was a typo in the implementation compared to the rest of the implementations.
=> Fixed error in compressing lz4raw with large offsets

src/compression.rs
Follow-up of #140, which was a consequence of similar implementations not being lifted to common logic.
=> Lifted duplicated code to a function

src/lib.rs, src/read/metadata.rs, src/read/stream.rs, src/write/file.rs, src/write/mod.rs, src/write/stream.rs, tests/it/write/indexes.rs, tests/it/write/mod.rs
* It was possible to call start multiple times, which would lead to `FileWriter.offset` to be out of sync with the file.
* `FileWriter::start` can no longer be called, and runtime errors are not returned by `FileWriter.write`.
* Synchronises async and sync api's for `FileWriter.end`. Sync can no longer write the footer twice.
* Reading parquet files didn't check the file size included the header
This is a breaking change
=> Fix potential misuse of FileWriter API's (sync + async)

src/read/metadata.rs, src/read/stream.rs, tests/it/read/mod.rs
This PR simplifies the (sync) reading of metadata by avoiding pushing thrift decoding to the underlying reader, instead decoding directly from a temp buffer.
This is generally a tradeoff (memory usage vs CPU usage), but it is generally recommended to not deserialize stuff directly from the IO if there is not a strong reason to - we already do this in the `async` version.
=> Improved read of metadata

.github/workflows/test.yml, Cargo.toml, src/encoding/delta_bitpacked/decoder.rs, src/read/mod.rs, src/read/page/mod.rs, src/write/mod.rs, src/write/page.rs, tests/it/read/primitive.rs
They are required by thrift and the crate does not compile without it, so we may as well make it required for simplicity
=> Removed unused cargo feature

examples/write_sidecar.rs, guide/src/README.md, src/write/file.rs, src/write/mod.rs, tests/it/write/mod.rs, tests/it/write/sidecar.rs
=> Added API to write sidecar

src/page/page_dict/mod.rs, src/read/metadata.rs, src/read/mod.rs, src/read/page/mod.rs, src/read/page/stream.rs, src/read/stream.rs
When streaming pages over the network it is quite awkward to fulfill the `AsyncSeek` constraint.
This PR exposes methods that work nicely with usages that only provide `AsyncRead` (for example, a [Rusoto S3 `StreamingBody`](https://rusoto.github.io/rusoto/rusoto_s3/struct.GetObjectOutput.html#structfield.body) /w `TryStreamExt::into_async_read`).
`cargo test` passes, but I note there are no tests that exercise the page filtering. A naive attempt to add additional pages in `test_column_async` didn't work. If the lack of tests here are of concern then I need some guidance on where/how to add them.
=> Removed `AsyncSeek` requirement from page stream

Cargo.toml, examples/read_metadata.rs, src/deserialize/binary.rs, src/deserialize/boolean.rs, src/deserialize/fixed_len.rs, src/deserialize/native.rs, src/deserialize/utils.rs, src/encoding/bitpacking.rs, src/encoding/hybrid_rle/decoder.rs, src/encoding/mod.rs, src/encoding/plain_byte_array.rs, src/metadata/column_chunk_metadata.rs, src/metadata/file_metadata.rs, src/page/mod.rs, src/page/page_dict/binary.rs, src/page/page_dict/fixed_len_binary.rs, src/page/page_dict/primitive.rs, src/read/page/reader.rs, src/read/page/stream.rs, src/schema/io_thrift/from_thrift.rs, tests/it/read/binary.rs, tests/it/read/boolean.rs, tests/it/read/fixed_binary.rs, tests/it/read/mod.rs, tests/it/read/primitive.rs, tests/it/read/primitive_nested.rs, tests/it/read/struct_.rs, tests/it/read/utils.rs
Removed all panics on invalid data:
* reading schemas is now panic free (there was a bug in the thrift deserialization causing a panic on invalid union input)
* invalid lengths of v1 page of rep and def buffers
* negative compressed and uncompressed sizes in pages
* invalid `i32 -> usize` casts
* invalid RLE-encoded data
* invalid num_bits declarations
It is still possible to abort on OOM when reading invalid pages - when we read pages, we should be aware of the total column size or something and avoid reading pages larger than the file size. We need to think a bit on how we wanna do this.
=> Removed panics on read

src/bloom_filter/read.rs, src/error.rs, src/read/indexes/read.rs, src/read/metadata.rs, src/read/page/indexed_reader.rs, src/read/page/reader.rs, src/read/page/stream.rs, src/read/stream.rs
This PR improves the performance of reading (everything) by not zeroying regions when calling `Read`, via `read_to_end`.
Excellent tip by [Kornel](https://users.rust-lang.org/u/kornel/summary) at https://users.rust-lang.org/t/how-to-efficiently-re-use-a-vec-u8-for-multiple-read-read/77628/6
=> Improved performance of reading

src/compression.rs, tests/it/read/lz4_legacy.rs, tests/it/read/mod.rs
=> Supports legacy lz4 decompression

src/write/compression.rs
Allows users to re-use the compressor's buffer.
=> Added `Compressor::into_inner`

parquet-tools/Cargo.toml, parquet-tools/src/lib/dump.rs, parquet-tools/src/lib/meta.rs, src/page/mod.rs
I noticed that the `parquet-tools` crate not longer compiles because of some api changes. This is my quick attempt at fixing it.
=> Fix compilation of parquet-tools

src/write/stream.rs
=> Fixed FileStreamer's end method to flush Parquet magic

Cargo.toml
This PR proposes to use the zlib-ng backend for gzip. It is up 2.5x faster than the default backend. Some benchmarks here:
https://github.com/Byron/gitoxide/issues/1#issuecomment-672626465.
~Maybe you want to optional as feature flag?~
Edit: made it an optional feature flag
=> Add zlib-ng backend for gzip

src/compression.rs, src/parquet_bridge.rs
It is an implementation detail of the crate that has no use outside it.
=> Privatized `CompressionLevel`

.github/workflows/coverage.yml, .github/workflows/test.yml, Cargo.toml, src/read/mod.rs, src/read/page/mod.rs, src/write/column_chunk.rs, src/write/indexes/write.rs, src/write/mod.rs, src/write/page.rs, src/write/row_group.rs
This PR makes `async` optional, to reduce the dependency tree.
Users must how pass the feature `async` to activate all async functionality.
=> Optional `async`

src/encoding/delta_bitpacked/decoder.rs, src/encoding/hybrid_rle/bitmap.rs, src/encoding/hybrid_rle/decoder.rs, src/encoding/hybrid_rle/mod.rs, src/encoding/mod.rs
Also simplified their internal code
=> Improved decoding documentation

src/schema/types/spec.rs
fuzzing found a multiplication overflow here:
https://github.com/jorgecarleitao/parquet2/blob/7caafa4ddc7c00dc81038736829e9e973611f956/src/schema/types/spec.rs#L44
so I changed it to a `checked_mul` and also realized the subtract 1 could underflow also. the fuzzer didn't confirm, but the rust compiler did:
```rs
error: this arithmetic operation will overflow
--> src/main.rs:2:20
|
2 |     println!("{}", (i32::MIN / 8) * 8 - 1);
|                    ^^^^^^^^^^^^^^^^^^^^^^ attempt to compute `i32::MIN - 1_i32`, which would overflow
=> FixedLenByteArray max_precision integer overflow

src/compression.rs, src/error.rs, src/read/compression.rs, src/read/page/reader.rs
fuzzing was turning up errors again, so I am making best-guess fixes (one per commit)
let me know if any of my fixes are the wrong idea and I can fix it up!
=> Replaced panics by errors on invalid pages

src/encoding/hybrid_rle/mod.rs
During an optimization pass I noticed there were still checked `Index` calls in this function where they could be elided.
=> elide bound check in RLE decoder

src/write/column_chunk.rs, src/write/file.rs, src/write/stream.rs
As per: https://github.com/jorgecarleitao/parquet2/issues/199
Only two places where this would be a problem, sync and async version of the same method. TCompactOutputProtocol writes to the inner writer, which might or not might not be a buffered writer. Either way, performs better!
There are additional places where flushes are performed, specifically after writing the footer, but I could not see a good reason to remove that. Posssibly if you were sending multiple files over some type of transport where you wanted to optimize things? But even then, you would have to have quite small files for this to even remotely matter. Either way, I did note that this flush was only performed on the async implementation, so I added it to the sync version as well for consistencies sake.
=> Removed unnecessary flushes while writing

src/encoding/hybrid_rle/mod.rs
fixes https://github.com/jorgecarleitao/arrow2/issues/1327
@jorgecarleitao could we patch this one? I think it is serious enough.
I'd like to add a test for this one, but I don't (yet) know parquet enough to to setup these conditions
=> Fixed error in rle decoding

Cargo.toml
Hi @jorgecarleitao!  I noticed a compiler error while upgrading arrow2 in a separate project that uses async-stream version `0.3.2`.  The other project's usage of version `0.3.2` led to arrow2 and parquet2 both using it, which then led to a compiler error.  I looked into it and found that async-stream's `0.3.3` [release](https://github.com/tokio-rs/async-stream/releases/tag/v0.3.3) contains a fix that parquet2 relies on.  So this PR bumps parquet2's minimum async-stream version to `0.3.3` to include the fix.
Here is the code that fails to compile with async-stream `0.3.2`.
https://github.com/jorgecarleitao/parquet2/blob/ac31d0e8140c518509091c1ad17b9d716a728a70/src/read/page/stream.rs#L120-L126
Here is the resulting error: 
```
error[E0277]: the `?` operator can only be used in an async …
```
=> Bump minimum async-stream version to 0.3.3

src/read/metadata.rs, src/schema/types/spec.rs
fix decimal values can not be inserted when scale is equal to precision.
According to [parquet format](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal), Scale must be zero or a positive integer less than or equal to the precision.
=> fix check decimal scale equal to precision
